#!/usr/bin/env sh

export _JAVA_AWT_WM_NONREPARENTING=1
feh --bg-fill --no-fehbg $HOME/Pictures/Wallpapers/1705116498518910.jpg
remapd &
dunst &
mpd &
picom --corner-radius=20 --daemon
dwmblocks &
clipmenud &
xset dpms 0 0 0
xset s off -dpms
