vim.cmd('au BufNewFile, BufRead *.tex set filetype=tex')
vim.cmd('au BufNewFile, BufRead *.md set filetype=markdown')
vim.cmd('au BufNewFile, BufRead *.py set filetype=python')
vim.cmd('au BufNewFile, BufRead *.rem set filetype=remind')
vim.cmd('au BufNewFile, BufRead *.sh set filetype=zsh')
vim.cmd('au BufNewFile, BufRead *.html set filetype=html')
vim.cmd('au BufNewFile, BufRead *.js set filetype=javascript')
vim.cmd('au BufNewFile, BufRead *.css set filetype=css')
